#ifndef __ASSEMBLER__
extern const uint8_t NMI_ROM[];
extern const uint32_t NMI_ROM_SIZE;
#endif
#define ACTION_READ_DATA_FROM_PICO 10
#define ACTION_WRITE_DATA_TO_PICO 9
#define ACTION_ROM_CHANGE 8
#define ACTION_ROM_LIST 7
#define ACTION_SNA_SAVE 6
#define ACTION_SNA_LIST 5
#define ACTION_SNAP_NEXT_WRITE 4
#define ACTION_SNAP_BEGIN_WRITE 3
#define ACTION_SNAP_READ_NEXT 2
#define ACTION_BEGIN_SNAP_READ 1
#define EXITNMI 0x128
#define STARTUP_COMMAND_OFFSET 0x12a
#define STARTUP_PARAM1_OFFSET 0x12b
#define STARTUP_PARAM2_OFFSET 0x12d
#define STARTUP_ACTION_LOAD_MEMORY 0x4
#define STARTUP_ACTION_SAVE_MEMORY 0x3
#define STARTUP_ACTION_LOAD_SNAP 0x2
#define STARTUP_ACTION_TRANSFER_SNAP 0x1
