extern const uint8_t NMI_ROM[];
extern const uint32_t NMI_ROM_SIZE;
extern const uint32_t EXITNMI;
#define STARTUP_COMMAND_OFFSET 0x10e
#define STARTUP_PARAM1_OFFSET 0x10f
#define STARTUP_PARAM2_OFFSET 0x111
#define STARTUP_ACTION_LOAD_MEMORY 0x4
#define STARTUP_ACTION_SAVE_MEMORY 0x3
#define STARTUP_ACTION_LOAD_SNAP 0x2
#define STARTUP_ACTION_TRANSFER_SNAP 0x1
